Triage automation: update token
GitHub bug means that GITHUB_TOKEN doesn't work according to
documentation at https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token because it doesn't have the right permissions for moving stuff to a project board.

The automation throws this error:
Error: Resource not accessible by integration

Use our own generated token for now.

Signed-off-by: Ekaterina Gerasimova <kittykat3756@gmail.com>